version: '3.4'

services:
  api_gateway:
    image: ${DOCKER_REGISTRY-}api_gateway
    build:
      context: ./api_gateway
      dockerfile: ./Dockerfile

  order_api:
    image: ${DOCKER_REGISTRY-}order_api
    build:
      context: ./order_api
      dockerfile: ./Dockerfile
    restart: always

  product_api:
    image: ${DOCKER_REGISTRY-}product_api
    build:
      context: ./product_api
      dockerfile: ./Dockerfile

  customer_api:
    image: ${DOCKER_REGISTRY-}customer_api
    build:
      context: ./customer_api
      dockerfile: ./Dockerfile